management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
logging:
  file: rmvote.log

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  profiles:
    active: dev