spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:rmvote.backend
    url: jdbc:h2:mem:rmvote.backend
    driverClassName: org.h2.Driver
    username: sa
    password: ''
liquibase:
  user: rmvote
  password:
admin:
  token: caa6d33c-26c9-4bde-b6ff-b2cd2b45bed0

