spring:
  datasource:
    url: jdbc:postgresql://192.168.196.173:5432/postgres
    driverClassName: org.postgresql.Driver
    username: rmvote
    password: rmvote
liquibase:
  user: rmvote
  password: rmvote
admin:
  token: caa6d33c-26c9-4bde-b6ff-b2cd2b45bed0
