logging:
  file: rmvote.log

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  profiles:
    active: dev
